<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <BaseOutputPath>..\..\Artifacts\Xna.Framework.Content.Pipeline.Graphics.MojoProcessor\</BaseOutputPath>
    
    <Version>3.14.9001.0</Version>
    <AssemblyVersion>3.14.9001.0</AssemblyVersion>

  </PropertyGroup>

  <PropertyGroup>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <TargetFrameworks>net40;netstandard2.0;net8.0</TargetFrameworks>
    <LangVersion>5</LangVersion>
    <AssemblyName>Xna.Framework.Content.Pipeline.Graphics.MojoProcessor</AssemblyName>
    <RootNamespace>Microsoft.Xna.Framework.Content.Pipeline.Graphics</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DefineConstants></DefineConstants>
    <NoWarn>CS0067;CS1591;CS1574;CS0419</NoWarn>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net40' ">
    <Reference Include="SharpDX">
      <HintPath>..\..\ThirdParty\SharpDX\4.0.1\net40\SharpDX.dll</HintPath>
    </Reference>
    <Reference Include="SharpDX.D3DCompiler">
      <HintPath>..\..\ThirdParty\SharpDX\4.0.1\net40\SharpDX.D3DCompiler.dll</HintPath>
    </Reference>
    <Reference Include="CppNet">
      <HintPath>..\..\ThirdParty\CppNet\net40\CppNet.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0' Or '$(TargetFramework)' == 'net8.0' ">
    <Reference Include="SharpDX">
      <HintPath>..\..\ThirdParty\SharpDX\4.0.1\netstandard1.3\SharpDX.dll</HintPath>
    </Reference>
    <Reference Include="SharpDX.D3DCompiler">
      <HintPath>..\..\ThirdParty\SharpDX\4.0.1\netstandard1.3\SharpDX.D3DCompiler.dll</HintPath>
    </Reference>
    <Reference Include="CppNet">
      <HintPath>..\..\ThirdParty\CppNet\net40\CppNet.dll</HintPath>
    </Reference>

  </ItemGroup>

  <ItemGroup>
    <Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>
  
  <ItemGroup>
    <Compile Include="Processors\EffectProcessor.cs" />
    <Compile Include="Processors\EffectProcessorDebugMode.cs" />
    <Compile Include="EffectCompiler\ConstantBufferData.cs" />
    <Compile Include="EffectCompiler\EffectObject.cs" />
    <Compile Include="EffectCompiler\EffectObjectWriter.cs" />
    <Compile Include="EffectCompiler\MarshalHelper.cs" />
    <Compile Include="EffectCompiler\SamplerInfo.cs" />
    <Compile Include="EffectCompiler\ShaderCompilerException.cs" />
    <Compile Include="EffectCompiler\ShaderData.cs" />
    <Compile Include="EffectCompiler\MojoShader.cs" />
    <Compile Include="EffectCompiler\Preprocessor.cs" />
    <Compile Include="EffectCompiler\ShaderProfile.cs" />
    <Compile Include="EffectCompiler\ShaderProfileDX11.cs" />
    <Compile Include="EffectCompiler\ShaderProfileGL.cs" />
    <Compile Include="EffectCompiler\ShaderProfileType.cs" />
    <Compile Include="EffectCompiler\ShaderStage.cs" />
    <Compile Include="EffectCompiler\ShaderVersion.cs" />
    <Compile Include="RawGlsl\RawGlslEffectContent.cs" />
    <Compile Include="RawGlsl\RawGlslEffectImporter.cs" />
    <Compile Include="RawGlsl\RawGlslEffectProcessor.cs" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="ExternalTool.cs" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\..\Platforms\Platform\Utilities\CurrentPlatform.cs">
      <Link>Utilities\CurrentPlatform.cs</Link>
    </Compile>
    <Compile Include="..\..\Platforms\Utilities\Hash.cs">
      <Link>Utilities\Hash.cs</Link>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\ThirdParty\Dependencies\MojoShader\Windows\libmojoshader_64.dll">
      <Link>libmojoshader_64.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <NativeBinary>True</NativeBinary>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Xna.Framework\Xna.Framework.csproj">
      <Project>{741B4B1E-89E4-434C-8867-6129838AFD51}</Project>
      <Name>Xna.Framework</Name>
      <Private>False</Private>
    </ProjectReference>
    <ProjectReference Include="..\Xna.Framework.Graphics\Xna.Framework.Graphics.csproj">
      <Project>{4B8D3F73-BBD2-4057-B86B-8B73B957DC0F}</Project>
      <Name>Xna.Framework.Graphics</Name>
      <Private>False</Private>
    </ProjectReference>
    <ProjectReference Include="..\Xna.Framework.Content.Pipeline\Xna.Framework.Content.Pipeline.csproj">
      <Project>{73509F44-3566-4B79-BB47-C7C6E2AA2351}</Project>
      <Name>Xna.Framework.Content.Pipeline</Name>
      <Private>False</Private>
    </ProjectReference>
    <ProjectReference Include="..\Xna.Framework.Content.Pipeline.Graphics\Xna.Framework.Content.Pipeline.Graphics.csproj">
      <Project>{7a3fa1d0-1b03-49cb-9e1b-b9dbf27d74b1}</Project>
      <Name>Xna.Framework.Content.Pipeline.Graphics</Name>
      <Private>False</Private>
    </ProjectReference>
  </ItemGroup>

</Project>